//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pirettech.Pubs.WebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Livro()
        {
            this.LivroAutor = new HashSet<LivroAutor>();
        }
    
        public string LivroId { get; set; }
        public string Titulo { get; set; }
        public string Tipo { get; set; }
        public string EditoraId { get; set; }
        public Nullable<decimal> Preco { get; set; }
        public Nullable<decimal> Adiantamento { get; set; }
        public Nullable<int> royalty { get; set; }
        public Nullable<int> VendasAnuais { get; set; }
        public string Notas { get; set; }
        public System.DateTime DataPublicacao { get; set; }
    
        public virtual Editora Editora { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LivroAutor> LivroAutor { get; set; }
    }
}
